### ISSUE TITLE
AssertionError: some annotations uuid were not unique!

### ISSUE THREAD

**Issue by Bassmann** [thiswillbeyourgithub/LogseqPDFImporter#4]
This is the error when I try to run the python script. It happens both under Windows natively and WSL. First I got an error message that matplotlib couldn't be found which I installed manually.

Then I got the following output when running `python3 ./LogseqPDFImporter.py "<path to pdf>" --md_path "<md-file>" --edn_path "<edn-file>"`

```sh
{'page': 3, 'properties': {'color': 'yellow'}, 'position': {'bounding': {'x1': 72.0999984741211, 'y1': 186.833984375, 'x2': 350.2489929199219, 'y2': 218.8740234375, 'width': 612.0, 'height': 792.0}, 'rects': [{'x1': 72.0999984741211, 'y1': 186.833984375, 'x2': 350.2489929199219, 'y2': 218.8740234375, 'width': 612.0, 'height': 792.0}], 'page': 3}, 'content': {'text': ''}, 'id #uuid': 'fbb11cb3-fec3-3dea-8681-cdc95bdd4b66', 'author': 'username'}
{'page': 3, 'properties': {'color': 'yellow'}, 'position': {'bounding': {'x1': 72.0999984741211, 'y1': 234.9219970703125, 'x2': 357.5899963378906, 'y2': 289.114013671875, 'width': 612.0, 'height': 792.0}, 'rects': [{'x1': 72.0999984741211, 'y1': 234.9219970703125, 'x2': 357.5899963378906, 'y2': 289.114013671875, 'width': 612.0, 'height': 792.0}], 'page': 3}, 'content': {'text': ''}, 'id #uuid': 'fbb11cb3-fec3-3dea-8681-cdc95bdd4b66', 'author': 'username'}
{'page': 3, 'properties': {'color': 'yellow'}, 'position': {'bounding': {'x1': 72.0999984741211, 'y1': 387.0539855957031, 'x2': 361.0920104980469, 'y2': 431.0060119628906, 'width': 612.0, 'height': 792.0}, 'rects': [{'x1': 72.0999984741211, 'y1': 387.0539855957031, 'x2': 361.0920104980469, 'y2': 431.0060119628906, 'width': 612.0, 'height': 792.0}], 'page': 3}, 'content': {'text': ''}, 'id #uuid': 'fbb11cb3-fec3-3dea-8681-cdc95bdd4b66', 'author': 'username'}
{'page': 3, 'properties': {'color': 'yellow'}, 'position': {'bounding': {'x1': 72.0999984741211, 'y1': 611.8419799804688, 'x2': 353.6000061035156, 'y2': 631.7940063476562, 'width': 612.0, 'height': 792.0}, 'rects': [{'x1': 72.0999984741211, 'y1': 611.8419799804688, 'x2': 353.6000061035156, 'y2': 631.7940063476562, 'width': 612.0, 'height': 792.0}], 'page': 3}, 'content': {'text': ''}, 'id #uuid': 'fbb11cb3-fec3-3dea-8681-cdc95bdd4b66', 'author': 'username'}
{'page': 4, 'properties': {'color': 'yellow'}, 'position': {'bounding': {'x1': 72.0, 'y1': 226.81500244140625, 'x2': 535.343017578125, 'y2': 250.864990234375, 'width': 612.0, 'height': 792.0}, 'rects': [{'x1': 72.0, 'y1': 226.81500244140625, 'x2': 535.343017578125, 'y2': 250.864990234375, 'width': 612.0, 'height': 792.0}], 'page': 4}, 'content': {'text': ''}, 'id #uuid': 'fbb11cb3-fec3-3dea-8681-cdc95bdd4b66', 'author': 'username'}
{'page': 5, 'properties': {'color': 'yellow'}, 'position': {'bounding': {'x1': 72.0, 'y1': 292.8160095214844, 'x2': 493.50299072265625, 'y2': 316.7560119628906, 'width': 612.0, 'height': 792.0}, 'rects': [{'x1': 72.0, 'y1': 292.8160095214844, 'x2': 493.50299072265625, 'y2': 316.7560119628906, 'width': 612.0, 'height': 792.0}], 'page': 5}, 'content': {'text': ''}, 'id #uuid': 'fbb11cb3-fec3-3dea-8681-cdc95bdd4b66', 'author': 'username'}
{'page': 5, 'properties': {'color': 'yellow'}, 'position': {'bounding': {'x1': 143.23199462890625, 'y1': 338.0840148925781, 'x2': 279.2640075683594, 'y2': 365.8760070800781, 'width': 612.0, 'height': 792.0}, 'rects': [{'x1': 143.23199462890625, 'y1': 338.0840148925781, 'x2': 279.2640075683594, 'y2': 365.8760070800781, 'width': 612.0, 'height': 792.0}], 'page': 5}, 'content': {'text': ''}, 'id #uuid': 'fbb11cb3-fec3-3dea-8681-cdc95bdd4b66', 'author': 'username'}
{'page': 5, 'properties': {'color': 'yellow'}, 'position': {'bounding': {'x1': 386.23199462890625, 'y1': 338.0840148925781, 'x2': 519.5150146484375, 'y2': 347.37200927734375, 'width': 612.0, 'height': 792.0}, 'rects': [{'x1': 386.23199462890625, 'y1': 338.0840148925781, 'x2': 519.5150146484375, 'y2': 347.37200927734375, 'width': 612.0, 'height': 792.0}], 'page': 5}, 'content': {'text': ''}, 'id #uuid': 'fbb11cb3-fec3-3dea-8681-cdc95bdd4b66', 'author': 'username'}
{'page': 5, 'properties': {'color': 'yellow'}, 'position': {'bounding': {'x1': 143.23199462890625, 'y1': 409.0119934082031, 'x2': 242.13499450683594, 'y2': 434.4280090332031, 'width': 612.0, 'height': 792.0}, 'rects': [{'x1': 143.23199462890625, 'y1': 409.0119934082031, 'x2': 242.13499450683594, 'y2': 434.4280090332031, 'width': 612.0, 'height': 792.0}], 'page': 5}, 'content': {'text': ''}, 'id #uuid': 'fbb11cb3-fec3-3dea-8681-cdc95bdd4b66', 'author': 'username'}
{'page': 5, 'properties': {'color': 'yellow'}, 'position': {'bounding': {'x1': 386.23199462890625, 'y1': 409.1440124511719, 'x2': 497.3160095214844, 'y2': 421.0719909667969, 'width': 612.0, 'height': 792.0}, 'rects': [{'x1': 386.23199462890625, 'y1': 409.1440124511719, 'x2': 497.3160095214844, 'y2': 421.0719909667969, 'width': 612.0, 'height': 792.0}], 'page': 5}, 'content': {'text': ''}, 'id #uuid': 'fbb11cb3-fec3-3dea-8681-cdc95bdd4b66', 'author': 'username'}
{'page': 5, 'properties': {'color': 'yellow'}, 'position': {'bounding': {'x1': 143.23199462890625, 'y1': 505.7300109863281, 'x2': 273.62200927734375, 'y2': 517.5260009765625, 'width': 612.0, 'height': 792.0}, 'rects': [{'x1': 143.23199462890625, 'y1': 505.7300109863281, 'x2': 273.62200927734375, 'y2': 517.5260009765625, 'width': 612.0, 'height': 792.0}], 'page': 5}, 'content': {'text': ''}, 'id #uuid': 'fbb11cb3-fec3-3dea-8681-cdc95bdd4b66', 'author': 'username'}
{'page': 5, 'properties': {'color': 'yellow'}, 'position': {'bounding': {'x1': 386.23199462890625, 'y1': 505.7300109863281, 'x2': 538.5360107421875, 'y2': 517.5260009765625, 'width': 612.0, 'height': 792.0}, 'rects': [{'x1': 386.23199462890625, 'y1': 505.7300109863281, 'x2': 538.5360107421875, 'y2': 517.5260009765625, 'width': 612.0, 'height': 792.0}], 'page': 5}, 'content': {'text': ''}, 'id #uuid': 'fbb11cb3-fec3-3dea-8681-cdc95bdd4b66', 'author': 'username'}
{'page': 5, 'properties': {'color': 'yellow'}, 'position': {'bounding': {'x1': 72.0, 'y1': 634.16796875, 'x2': 539.52197265625, 'y2': 729.4400024414062, 'width': 612.0, 'height': 792.0}, 'rects': [{'x1': 72.0, 'y1': 634.16796875, 'x2': 539.52197265625, 'y2': 729.4400024414062, 'width': 612.0, 'height': 792.0}], 'page': 5}, 'content': {'text': ''}, 'id #uuid': 'fbb11cb3-fec3-3dea-8681-cdc95bdd4b66', 'author': 'username'}
Traceback (most recent call last):
  File "/mnt/c/Users/username/Documents/LogseqPDFImporter/./LogseqPDFImporter.py", line 376, in <module>
    inst = fire.Fire(main)
  File "/home/user/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/user/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/c/Users/username/Documents/user/LogseqPDFImporter/./LogseqPDFImporter.py", line 305, in main
    assert len(ids) == len(set(ids)), "some annotations uuid were not unique!"
AssertionError: some annotations uuid were not unique!
```

I used FoxitPDF for annotating. Any idea what mistake I make?

**Comment by thiswillbeyourgithub** [comment]
Hi. I'm in a rush but in somecases the uuid is not random but a hash of the content of the annot. This is because exact duplicates of annotations are not really supposed to happen,hence why I added a check for uniqueness. Let me know if that helps

**Comment by thiswillbeyourgithub** [comment]
Also I dont know why matplotlib would be needed

**Comment by Bassmann** [comment]
> Hi. I'm in a rush but in somecases the uuid is not random but a hash of the content of the annot. This is because exact duplicates of annotations are not really supposed to happen,hence why I added a check for uniqueness. Let me know if that helps

Meanwhile I think it's an issue with thhe PDFReader. I tried SumatraPDF to annotate a file and that worked fine

**Comment by Bassmann** [comment]
> Also I dont know why matplotlib would be needed

Looks like colour-science wanted it

**Comment by Bassmann** [comment]
Since it works with another PDF reader app it can be closed. 

Thanks a lot for the immediate response and a happy new year!

**Comment by thiswillbeyourgithub** [comment]
You too! Don't hesitate to open more issues that will help others
